import {useCallback,useState} from 'react'
import {useSSE,SSEEvent} from './hooks/useSSE'
interface Question{field:string;label:string;type:string;options?:string[];required?:boolean}
interface Run{run_id:string;status:string;job_url:string;questions?:Question[];receipt?:Record<string,string>;confirmation_text?:string;reason?:string}
const hosts:Record<string,string>={'jobs.lever.co':'Lever','job-boards.greenhouse.io':'Greenhouse','jobs.ashbyhq.com':'Ashby','apply.workable.com':'Workable'}
function ats(url:string){try{return hosts[new URL(url).hostname]||''}catch{return ''}}
function App(){const[jobUrl,setJobUrl]=useState('');const[file,setFile]=useState<File|null>(null);const[runs,setRuns]=useState<Run[]>([]);const[notice,setNotice]=useState('');const[custom,setCustom]=useState('{}');
 useSSE(useCallback((event:SSEEvent)=>{setRuns(rs=>rs.map(r=>r.run_id===event.run_id?{...r,status:event.status,questions:(event.payload.questions as Question[]),receipt:event.payload.receipt as Record<string,string>,confirmation_text:event.payload.confirmation_text as string,reason:event.payload.reason as string}:r));setNotice(event.status==='NEEDS_INPUT'?'Required answers are ready.':event.status==='SUBMITTED'?'Application submitted.':'Application failed.')},[]))
 async function apply(){if(!ats(jobUrl)||!file)return setNotice('Enter a supported ATS URL and choose a PDF resume.');const profile=JSON.parse(custom||'{}');const data=await file.arrayBuffer();let binary='';new Uint8Array(data).forEach(b=>binary+=String.fromCharCode(b));const resume_pdf_b64=btoa(binary);const response=await fetch('/apply',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({job_url:jobUrl,profile,resume_pdf_b64})});const result=await response.json();setRuns(rs=>[{...result,job_url:jobUrl},...rs]);}
 async function resume(run:Run){const answers:Record<string,string>={};(run.questions||[]).forEach(q=>{const value=window.prompt(q.label+(q.options?' ('+q.options.join(', ')+')':''));if(value)answers[q.field]=value});const response=await fetch('/apply/'+run.run_id+'/resume',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({answers})});const result=await response.json();setRuns(rs=>rs.map(r=>r.run_id===run.run_id?{...r,...result}:r))}
 return <main><header><h1>Auto-Apply Engine</h1><span>Live via SSE</span></header><section><h2>New Application</h2><label>Job posting URL<input value={jobUrl} onChange={e=>setJobUrl(e.target.value)} placeholder="https://jobs.lever.co/..."/></label>{ats(jobUrl)&&<p>Detected: {ats(jobUrl)}</p>}<label>PDF resume<input type="file" accept="application/pdf" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><label>Profile JSON<textarea value={custom} onChange={e=>setCustom(e.target.value)}/></label><button onClick={apply}>Apply</button>{notice&&<p>{notice}</p>}</section>{runs.map(run=><section key={run.run_id}><strong>{run.status}</strong><p>{run.job_url}</p>{run.status==='NEEDS_INPUT'&&<button onClick={()=>resume(run)}>Answer all questions</button>}{run.status==='SUBMITTED'&&<pre>{JSON.stringify(run.receipt,null,2)}</pre>}{run.status==='FAILED'&&<p>{run.reason}</p>}</section>)}</main>}
export default App
